### ISSUE TITLE
how can we use our table to store data ?

### ISSUE THREAD

**Issue by mojtaba-zolfaghari** [hamed-shirbandi/DbLogger.Core#1]
hi 
I recently use this , but I want to insert data into my table Not `AppLogInput.cs` and `AppLogOutput.cs `, how can I do that on npm version  of LoggerDb not core project ( I can not add core project on my solution)

**Comment by hamed-shirbandi** [comment]
this library is not to be used that way!
if you want to have your own table so you just can use my code and modify models and then use the local nuget package created by build event on release mode.

**Comment by mojtaba-zolfaghari** [comment]
I did that but The Logger dident Work on ERROR level

**Comment by hamed-shirbandi** [comment]
Same issue was reported in https://github.com/hamed-shirbandi/DbLogger.Core/issues/2
