### ISSUE TITLE
exeption handler now working when I set to options.logLevel = LogLevel.Error;

### ISSUE THREAD

**Issue by mojtaba-zolfaghari** [hamed-shirbandi/DbLogger.Core#2]
I called 
`            services.AddDbLogger(options =>
             {
                 options.logLevel = LogLevel.Error;
                 options.Path = "DbLogs";
                 options.ApplicationName = "Farabar Web Api ";
                 options.LogSize = 10000;
             });`
and create fake error (number/0) but when 
`            if (!IsEnabled(logLevel))
            {
                return;
            }`
called it always return information and go to return and skip adding to db @hamed-shirbandi

**Comment by hamed-shirbandi** [comment]
i think you are using the source code by coping it into your project so i cant guess what you done and cant help you in this case.
please give me more info or try to use the Nuget package.

**Comment by mojtaba-zolfaghari** [comment]
I download it from here and add into solution 
then reference it to my api project and config that like 
`            services.AddDbLogger(options =>
             {
                 options.logLevel = LogLevel.Error; 
                 options.Path = "DbLogs";
                 options.ApplicationName = "Web Api "; 
             });`
and 
`app.UseDbLogger();`
then edit table to my rows 
it's worked but the exception and log level didn't sent to LOG method on LoggerProvider and it's worked once I change log level to trace or information not Error

**Comment by mojtaba-zolfaghari** [comment]
you refrenced to topic to each other and no answer

**Comment by hamed-shirbandi** [comment]
sorry,im so busy this days.
i think that is a problem with your code.
i checked it again and every thing worked fine!
